name: EAS Build and Submit

on:
  push:
    branches:
      - main # Triggers when you push to the main branch

jobs:
  build_and_submit:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Build iOS App
        # To re-enable auto-submit, add the --auto-submit flag after configuring App Store Connect API Keys on Expo
        run: eas build --platform ios --profile production --non-interactive

      - name: 🚀 Build Android App
        # To re-enable auto-submit, add the --auto-submit flag after configuring Google Play Store credentials on Expo
        run: eas build --platform android --profile production --non-interactive
