name: EAS Build and Submit

on:
  push:
    branches:
      - main # Triggers when you push to the main branch

jobs:
  build_and_submit:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Build and Submit to iOS
        run: eas build --platform ios --profile production --auto-submit --non-interactive

      - name: 🚀 Build and Submit to Android
        run: eas build --platform android --profile production --auto-submit --non-interactive
